export enum ACTIONS {
  CONNECTION = 'CONNECTION',
  GET_ALL_REPOS = 'GET_ALL_REPOS',
  SET_TX_NOTIFY = 'SET_TX_NOTIFY',
  REMOVE_TX = 'REMOVE_TX',
  SET_TX = 'SET_TX',
  ERROR = 'ERROR',
  REPO_META = 'REPO_META',
  REPO_REFS = 'REPO_REFS',
  COMMIT = 'COMMIT',
  TREE_DATA = 'TREE_DATA',
  CREATE_REPOS = 'CREATE_REPOS',
  DELETE_REPOS = 'DELETE_REPOS',
  SET_FILE_TEXT = 'SET_FILE_TEXT'
}
